### ISSUE TITLE
自动登录无效？

### ISSUE THREAD

**Issue by zhzhongshi** [ryoii/mirai-console-plus#6]
```
[root@izne820n1d82x2z qqbot]# java -jar mirai-console-wrapper-1.1.0.jar
You are running Mirai-Console-Wrapper under /home/app/qqbot
All additional libraries are located at /home/app/qqbot/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Core Version: 1.0-RC | Newest STABLE Core Version: 1.0-RC
Local Console-Pure Version: 0.5.1 | Newest STABLE Console-Pure Version: 0.5.1
Version check complete, starting Mirai
shadow-Protocol:/home/app/qqbot/content/mirai-core-qqandroid-jvm-1.0-RC.jar
Console        :/home/app/qqbot/content/mirai-console-0.5.1.jar
Root           :/home/app/qqbot/
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] Mirai-console now running under /home/app/qqbot
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] Get news in github: https://github.com/mamoe/mirai
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] Powered by Mamoe Technologies and contributors
 21:57:08 [INFO] [Plugin Manager] 开始加载/home/app/qqbot/plugins/下的插件
 21:57:08 [INFO] [Plugin Manager] loading plugin ConsoleAddition
 21:57:08 [INFO] [Plugin Manager] successfully loaded plugin ConsoleAddition version V0.2.3 by ryoii
 21:57:08 [INFO] [Plugin Manager] Mirai-console的增强插件，添加若干常用的命令
 21:57:08 [INFO] [Plugin Manager] loading plugin Forward
 21:57:08 [INFO] [Plugin Manager] successfully loaded plugin Forward version 0.1.2 by HelloWorld
 21:57:08 [INFO] [Plugin Manager]
 21:57:08 [INFO] [Plugin Manager] loading plugin MiraiAPIHTTP
 21:57:08 [INFO] [Plugin Manager] successfully loaded plugin MiraiAPIHTTP version v1.6.5 by ryoii
 21:57:08 [INFO] [Plugin Manager] Mirai HTTP API Server Plugin
 21:57:08 [INFO] [Plugin Manager] loading plugin Ghs
 21:57:08 [INFO] [Plugin Manager] successfully loaded plugin Ghs version 0.1.0 by evrstr
 21:57:08 [INFO] [Plugin Manager] ghs插件
 21:57:08 [INFO] [ConsoleAddition] 3173857429
 21:57:08 [INFO] [ConsoleAddition] 读取了1个bot信息
 21:57:08 [INFO] [MiraiAPIHTTP] Loading Mirai HTTP API plugin
 21:57:08 [INFO] [MiraiAPIHTTP] Trying to Start Mirai HTTP Server in 0.0.0.0:5710
 21:57:08 [INFO] [ConsoleAddition] 正在自动登录3173857429
 21:57:08 [INFO] [Forward] 转发插件加载
 21:57:08 [INFO] [MiraiAPIHTTP] Starting Mirai HTTP Server in 0.0.0.0:5710
Exception in thread "DefaultDispatcher-worker-1" net.mamoe.mirai.console.command.UnknownCommandException: unknown command "/login-md5"
        at net.mamoe.mirai.console.command.CommandManager.processCommandImpl(CommandManager.kt:170)
        at net.mamoe.mirai.console.command.CommandManager$processCommand$2.invokeSuspend(CommandManager.kt:146)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Mirai HTTP API 21:57:08 : Http api server is running with authKey: 3173857429
 21:57:08 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: false
 21:57:08 [INFO] [MiraiAPIHTTP] 上报模块启用状态: false
 21:57:08 [INFO] [Ghs] PingMyMCServer Enabled
 21:57:08 [INFO] [Plugin Manager] 加载了4个插件
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] Mirai-console 启动完成
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] "/login qqnumber qqpassword " to login a bot
 21:57:08 [INFO] [Mirai 0.5.1 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
```

**Comment by ryoii** [comment]
console修改了命令规则，等console稳定后，再进行更新

**Comment by ryoii** [comment]
done
